version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USER_NAME}/ui:${VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - frontend_net
  post:
    image: ${USER_NAME}/post:${VERSION}
    networks:
      - backend_net
      - frontend_net
  comment:
    image: ${USER_NAME}/comment:${VERSION}
    networks:
      - backend_net
      - frontend_net
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - backend_net
      - frontend_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - backend_net

volumes:
  post_db:
  prometheus_data:

networks:
  frontend_net:
  backend_net:
